In [20]:
import pandas as pd

In [21]:
df = pd.read_csv("../data/SmokingAndTobaccoData2018-enhanced.csv")

In [22]:
df

,Country,CigaretteSmokingPrevalence,TobaccoSmokingPrevalence,TobaccoUsePrevalance,DeathsBySmoking,HealthWarningsOnSmoking,TreatmentInHealthFacilities,MostSoldBrandCigarettePriceInUSD,GDPinUSD,Population
0,Albania,43.3,50.5,50.5,"4,304",No,Yes in some,NaN,11104.0,2877013.0
1,Algeria,11.1,14.5,18.8,"20,914",No,Yes in some,2.58,14228.0,41927007.0
2,Andorra,27.7,33.8,33.8,104,Not applicable,No,4.20,NaN,NaN
3,Argentina,19.2,21.1,21.8,"50,863",Yes,Yes in most,2.41,18556.0,44413596.0
4,Armenia,19.6,26.7,26.7,"4,829",Not applicable,Yes in some,1.41,11454.0,2836557.0
...,...,...,...,...,...,...,...,...,...,...
144,Uzbekistan,10.1,12.3,12.3,"21,961",No,Yes in some,NaN,11220.0,32449576.0
145,Vanuatu,2.4,20.1,3.3,242,Not applicable,No,6.87,NaN,297298.0
146,Yemen,20.7,26.9,32.5,"16,667",Yes,No,2.20,2285.0,30790513.0
147,Zambia,11.5,24.1,19.8,"4,597",No,Yes in some,1.71,3534.0,17835893.0
148,Zimbabwe,11.1,13.9,13.9,"8,699",No,No,1.75,1611.0,15052184.0

In [23]:
df.isna().sum()

Country                              0
CigaretteSmokingPrevalence           0
TobaccoSmokingPrevalence             0
TobaccoUsePrevalance                 0
DeathsBySmoking                     12
HealthWarningsOnSmoking              0
TreatmentInHealthFacilities          0
MostSoldBrandCigarettePriceInUSD    28
GDPinUSD                            26
Population                          13
dtype: int64

In [24]:
df.dtypes

Country                              object
CigaretteSmokingPrevalence          float64
TobaccoSmokingPrevalence            float64
TobaccoUsePrevalance                float64
DeathsBySmoking                      object
HealthWarningsOnSmoking              object
TreatmentInHealthFacilities          object
MostSoldBrandCigarettePriceInUSD    float64
GDPinUSD                            float64
Population                          float64
dtype: object